// MAX TIME v36 — persistent body/nutrition history + analytics
(function(){
  if(!S.measurements)S.measurements=[];
  if(!S.dailySummary)S.dailySummary={};
  function n(v){v=parseFloat(String(v).replace(',','.'));return Number.isFinite(v)?v:null}
  function dateLabel(k){const p=k.split('-');return p.length===3?`${p[2]}.${p[1]}`:k}
  function upsertMeasurement(field,value){const v=n(value);if(v===null)return;const d=todayKey();let r=S.measurements.find(x=>x.date===d);if(!r){r={date:d};S.measurements.push(r)}r[field]=v;S.profile[field]=v;S.measurements.sort((a,b)=>a.date.localeCompare(b.date));save();snapshotDay()}
  window.saveBodyMetric=function(field,value){upsertMeasurement(field,value);render()};
  function snapshotDay(){const d=todayKey(),t=totals(),g=calcMacros();S.dailySummary[d]={date:d,cal:+t.cal||0,p:+t.p||0,f:+t.f||0,c:+t.c||0,targetCal:+g.cal||0,targetP:+g.p||0,targetF:+g.f||0,targetC:+g.c||0,weight:n(S.profile.weight),waist:n(S.profile.waist)};save()}
  window.snapshotDay=snapshotDay;
  const oldSave=window.save||save;
  // Capture nutrition/body snapshot on every normal save without changing existing storage format.
  let snapLock=false;
  window.mtSnapshot=function(){if(snapLock)return;snapLock=true;try{const d=todayKey(),t=totals(),g=calcMacros();S.dailySummary[d]={date:d,cal:+t.cal||0,p:+t.p||0,f:+t.f||0,c:+t.c||0,targetCal:+g.cal||0,targetP:+g.p||0,targetF:+g.f||0,targetC:+g.c||0,weight:n(S.profile.weight),waist:n(S.profile.waist)};localStorage.setItem('max_time_v2',JSON.stringify({...S,timer:{on:false,left:0,max:0,ex:'',eid:null,mod:false,saved:false}}))}catch(e){}finally{snapLock=false}};
  document.addEventListener('click',()=>setTimeout(window.mtSnapshot,80),true);
  document.addEventListener('change',()=>setTimeout(window.mtSnapshot,80),true);
  window.addEventListener('pagehide',window.mtSnapshot);
  document.addEventListener('visibilitychange',()=>{if(document.hidden)window.mtSnapshot()});

  function measurements(){return (S.measurements||[]).slice().sort((a,b)=>a.date.localeCompare(b.date))}
  function lastVal(field){const a=measurements().filter(x=>n(x[field])!==null);return a.length?n(a[a.length-1][field]):null}
  function delta(field,days){const a=measurements().filter(x=>n(x[field])!==null);if(a.length<2)return null;const last=a[a.length-1],cut=new Date(last.date+'T12:00:00');cut.setDate(cut.getDate()-days);let first=a[0];for(const x of a){if(new Date(x.date+'T12:00:00')>=cut){first=x;break}}return +(n(last[field])-n(first[field])).toFixed(1)}
  function avgWeight7(){const a=measurements().filter(x=>n(x.weight)!==null).slice(-7);return a.length?+(a.reduce((s,x)=>s+n(x.weight),0)/a.length).toFixed(1):null}
  function foodDays(){return Object.values(S.dailySummary||{}).filter(x=>x&&x.date).sort((a,b)=>a.date.localeCompare(b.date))}
  function nutrition7(){const a=foodDays().slice(-7);if(!a.length)return null;return {days:a.length,cal:Math.round(a.reduce((s,x)=>s+(+x.cal||0),0)/a.length),target:Math.round(a.reduce((s,x)=>s+(+x.targetCal||0),0)/a.length),p:Math.round(a.reduce((s,x)=>s+(+x.p||0),0)/a.length)}}
  function trainStats(){const keys=Object.keys(S.train||{}),dates=new Set(),done=[];for(const k of keys){const m=k.match(/^(\d{4}-\d{2}-\d{2})_(.+)$/);if(!m)continue;const sets=S.train[k]||[],c=sets.filter(x=>x.done).length;if(c){dates.add(m[1]);done.push(...sets.filter(x=>x.done))}}return {days:dates.size,sets:done.length}}
  function exerciseProgress(){const rows=[];for(let d=1;d<=5;d++)for(const ex of P[d].ex){const entries=Object.keys(S.train||{}).filter(k=>k.endsWith('_'+ex.id)).sort().map(k=>({date:k.slice(0,10),sets:S.train[k]})).filter(x=>x.sets&&x.sets.some(s=>s.done));if(entries.length<2)continue;const score=e=>{const ss=e.sets.filter(s=>s.done);let load=0,reps=0;for(const s of ss){const l=parseFloat(s.load);if(Number.isFinite(l))load+=l*(+s.reps||0);reps+=(+s.reps||0)}return load||reps};const first=score(entries[0]),last=score(entries[entries.length-1]);if(first>0)rows.push({name:ex.n,pct:Math.round((last-first)/first*100),sessions:entries.length})}return rows.sort((a,b)=>b.sessions-a.sessions).slice(0,6)}
  function spark(values){if(values.length<2)return '<div class="analytics-empty">Нужно минимум 2 замера</div>';const w=300,h=70,min=Math.min(...values),max=Math.max(...values),range=max-min||1,pts=values.map((v,i)=>`${(i/(values.length-1))*w},${h-8-((v-min)/range)*(h-16)}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="3" vector-effect="non-scaling-stroke"/></svg>`}
  function insight(){const wd=delta('weight',28),wa=delta('waist',28),nw=nutrition7();if(wd===null||wa===null)return 'Собираем базу. Для нормального вывода нужны регулярные вес и талия минимум 2–4 недели.';if(wa<0&&Math.abs(wd)<=1)return `Рекомпозиция идёт в нужную сторону: талия ${wa} см, вес ${wd>0?'+':''}${wd} кг. Калории пока не меняем.`;if(wa>1&&wd>1)return 'Вес и талия растут одновременно. Если тренд сохранится 2 недели, профицит слишком высокий.';if(wd<-1.5)return 'Вес снижается быстро. Следим за силовыми и восстановлением; при их падении потребуется добавить калории.';return 'Пока выраженного сигнала для изменения калорийности нет. Продолжаем собирать данные.'}
  window.renderAnalytics=function(){const ms=measurements(),w=ms.filter(x=>n(x.weight)!==null),wa=ms.filter(x=>n(x.waist)!==null),nw=nutrition7(),ts=trainStats(),ep=exerciseProgress(),lw=lastVal('weight'),lWa=lastVal('waist'),dW=delta('weight',28),dWa=delta('waist',28);return `<h1>АНАЛИТИКА</h1><div class="note">MAX TIME собирает историю тренировок, питания, веса и талии. Чем длиннее история, тем полезнее выводы.</div><div class="card analytics-hero"><b>ТЕКУЩИЙ СТАТУС</b><div class="analytics-kpis"><span><strong>${lw??'—'}</strong><small>вес, кг</small></span><span><strong>${avgWeight7()??'—'}</strong><small>средний 7 дн.</small></span><span><strong>${lWa??'—'}</strong><small>талия, см</small></span><span><strong>${ts.sets}</strong><small>подходов</small></span></div><div class="analytics-insight">${insight()}</div></div><div class="card"><b>ВЕС</b><div class="analytics-change">28 дней: ${dW===null?'недостаточно данных':(dW>0?'+':'')+dW+' кг'}</div>${spark(w.slice(-30).map(x=>n(x.weight)))}</div><div class="card"><b>ТАЛИЯ</b><div class="analytics-change">28 дней: ${dWa===null?'недостаточно данных':(dWa>0?'+':'')+dWa+' см'}</div>${spark(wa.slice(-12).map(x=>n(x.waist)))}</div><div class="card"><b>ПИТАНИЕ · ПОСЛЕДНИЕ 7 ДНЕЙ</b>${nw?`<div class="analytics-kpis three"><span><strong>${nw.cal}</strong><small>ккал/день</small></span><span><strong>${nw.target}</strong><small>цель</small></span><span><strong>${nw.p}</strong><small>белок/день</small></span></div><div class="nutrition-rule">Заполнено дней: ${nw.days}/7</div>`:'<div class="analytics-empty">Пока нет сохранённой истории питания</div>'}</div><div class="card"><b>ТРЕНИРОВКИ</b><div class="nutrition-rule">Тренировочных дней в истории: ${ts.days} · выполненных подходов: ${ts.sets}</div>${ep.length?ep.map(x=>`<div class="analytics-row"><span>${x.name}<small>${x.sessions} тренировок</small></span><strong class="${x.pct>=0?'pos':'neg'}">${x.pct>=0?'+':''}${x.pct}%</strong></div>`).join(''):'<div class="analytics-empty">Для сравнения упражнения нужно выполнить минимум дважды</div>'}</div><div class="card"><b>ИСТОРИЯ ЗАМЕРОВ</b>${ms.length?ms.slice(-12).reverse().map(x=>`<div class="analytics-row"><span>${dateLabel(x.date)}</span><strong>${x.weight??'—'} кг · ${x.waist??'—'} см</strong></div>`).join(''):'<div class="analytics-empty">Замеров пока нет</div>'}</div><div class="card"><b>МАКС — ТРЕНЕР</b><div class="nutrition-rule">Подготовлена база данных для будущего анализа ИИ: тренировки, питание, вес и талия уже сохраняются в единой истории. Сам чат подключим отдельным этапом через защищённый сервер — API-ключ в приложение помещать нельзя.</div></div>`};

  // Replace body metric inputs in nutrition with history-aware handlers.
  const oldRN=renderNutrition;renderNutrition=function(){let h=oldRN();h=h.replace(/onchange="S\.profile\.weight=this\.value;save\(\);render\(\)"/g,'onchange="saveBodyMetric(\'weight\',this.value)"');h=h.replace(/onchange="S\.profile\.waist=this\.value;save\(\);render\(\)"/g,'onchange="saveBodyMetric(\'waist\',this.value)"');return h};

  const oldRender=render;render=function(){const app=document.getElementById('app');if(S.tab==='analytics'){app.innerHTML=topHtml()+`<main>${renderAnalytics()}</main>`+timerOverlay();tryPortrait();return}oldRender()};
  const oldTop=topHtml;topHtml=function(){let h=oldTop();h=h.replace('</div></div>',`<button class="tab ${S.tab==='analytics'?'on':''}" onclick="S.tab='analytics';save();render()">Аналитика</button></div></div>`);return h};
  const st=document.createElement('style');st.textContent=`.analytics-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.analytics-kpis.three{grid-template-columns:repeat(3,1fr)}.analytics-kpis span{background:#10141a;border:1px solid var(--line);border-radius:12px;padding:10px 5px;text-align:center}.analytics-kpis strong{display:block;font-size:19px}.analytics-kpis small{display:block;font-size:9px;color:var(--mut);margin-top:2px}.analytics-insight{margin-top:12px;padding:11px;border-radius:11px;background:var(--a12);border:1px solid var(--a20);font-size:12px;line-height:1.5;color:var(--a2)}.analytics-change{font-size:11px;color:var(--mut);margin-top:5px}.spark{width:100%;height:76px;color:var(--a);margin-top:10px}.analytics-row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.055);font-size:12px}.analytics-row:last-child{border-bottom:none}.analytics-row span small{display:block;color:var(--mut);font-size:9px;margin-top:2px}.analytics-row strong{font-size:12px;text-align:right}.analytics-row .pos{color:var(--ok)}.analytics-row .neg{color:var(--danger)}.analytics-empty{color:var(--mut);font-size:11px;padding:14px 0}.tabs{overflow-x:auto}.tab{min-width:max-content}@media(max-width:420px){.analytics-kpis{grid-template-columns:repeat(2,1fr)}.analytics-kpis.three{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(st);
  // Seed today's measurement from current profile only once, so future edits form a dated series.
  if(!localStorage.getItem('mt_measure_seed_v36')){S.measurements.push({date:todayKey(),weight:n(S.profile.weight),waist:n(S.profile.waist)});localStorage.setItem('mt_measure_seed_v36','1');save()}
  window.mtSnapshot();render();
})();