let S={tab:'training',day:Math.min(5,Math.max(1,new Date().getDay()||1)),hint:null,train:{},foods:[],foodSearch:'',foodForm:null,profile:{weight:80,height:178,age:48,activity:1.725,goal:0},history:[],timer:{on:false,left:0,max:0,ex:'',int:null}};

const K='max_time_v2';
function load(){try{const x=JSON.parse(localStorage.getItem(K));if(x)S={...S,...x};}catch(e){}if(!S.foods||!S.foods.length)S.foods=DEFAULT_FOODS}
function save(){localStorage.setItem(K,JSON.stringify(S))}
function todayKey(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function exKey(ex){return todayKey()+'_'+ex.id}
function getSets(ex){if(!S.train[exKey(ex)])S.train[exKey(ex)]=Array.from({length:ex.s},()=>({load:'',reps:'',rir:String(ex.r),done:false}));return S.train[exKey(ex)]}
function setField(ex,i,k,v){getSets(ex)[i][k]=v;save();render()}
function toggleSet(ex,i){getSets(ex)[i].done=!getSets(ex)[i].done;save();render()}
function progression(ex){const a=getSets(ex);return a.length===ex.s&&a.every(x=>x.done&&Number(x.reps)>=ex.max&&Number(x.rir)<=ex.r)}
function calcMacros(){const p=S.profile;const bmr=10*Number(p.weight)+6.25*Number(p.height)-5*Number(p.age)+5;const cal=Math.round(bmr*Number(p.activity)+(Number(p.goal)||0));return{cal,p:Math.round(Number(p.weight)*2.2),f:Math.round(cal*.25/9),c:Math.round((cal-Math.round(Number(p.weight)*2.2)*4-Math.round(cal*.25/9)*9)/4)}}
function dayFood(){const k='food_'+todayKey();if(!S[k])S[k]=[];return S[k]}
function totals(){return dayFood().reduce((a,x)=>({cal:a.cal+x.cal,p:a.p+x.p,f:a.f+x.f,c:a.c+x.c}),{cal:0,p:0,f:0,c:0})}
function addFood(id,g){const f=S.foods.find(x=>x.id===id),n=Number(g);if(!f||!n)return;dayFood().push({id:Date.now(),name:f.name,g:n,cal:Math.round(f.cal*n/100),p:+(f.p*n/100).toFixed(1),f:+(f.f*n/100).toFixed(1),c:+(f.c*n/100).toFixed(1)});save();render()}
function delFood(id){const k='food_'+todayKey();S[k]=dayFood().filter(x=>x.id!==id);save();render()}
function addCustomFood(){const x=S.foodForm;if(!x||!x.name)return;S.foods.push({id:'u'+Date.now(),name:x.name,cal:+x.cal||0,p:+x.p||0,f:+x.f||0,c:+x.c||0});S.foodForm=null;save();render()}
function exportData(){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='max-time-v2-'+todayKey()+'.json';a.click();URL.revokeObjectURL(u)}
function importData(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=e=>{const r=new FileReader();r.onload=ev=>{try{S={...S,...JSON.parse(ev.target.result)};save();render();alert('Данные восстановлены')}catch(x){alert('Ошибка файла')}};r.readAsText(e.target.files[0])};i.click()}

function fmtTime(sec){sec=Math.max(0,Math.round(sec));return Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0')}
function startTimer(sec,ex){stopTimer();S.timer={on:true,left:sec,max:sec,ex:ex,int:null};S.timer.int=setInterval(()=>{S.timer.left--;if(S.timer.left<=0){S.timer.left=0;stopTimer(false);try{navigator.vibrate&&navigator.vibrate([180,80,180])}catch(e){}}render()},1000);render()}
function stopTimer(close=true){if(S.timer&&S.timer.int)clearInterval(S.timer.int);if(!S.timer)S.timer={};S.timer.int=null;if(close)S.timer.on=false}
function adjTimer(v){S.timer.left=Math.max(0,S.timer.left+v);S.timer.max=Math.max(S.timer.max,S.timer.left);render()}
function timerOverlay(){if(!S.timer.on)return '';const warn=S.timer.left<=10,pct=S.timer.max?Math.max(0,Math.min(100,S.timer.left/S.timer.max*100)):0;return `<div class="overlay"><div class="tmr-card"><button class="tmr-close" onclick="stopTimer();render()">✕</button><div class="tmr-label">ОТДЫХ</div><div class="tmr-time ${warn?'warn':''}">${fmtTime(S.timer.left)}</div><div class="tmr-ex">${S.timer.ex}</div><div class="tmr-progress"><div class="tmr-bar" style="width:${pct}%"></div></div><div class="tmr-adj"><button class="adj-btn" onclick="adjTimer(-15)">−15С</button><button class="adj-btn" onclick="adjTimer(15)">+15С</button></div><button class="skip-btn" onclick="stopTimer();render()">ПРОПУСТИТЬ →</button></div></div>`}
function tryPortrait(){try{if(screen.orientation&&screen.orientation.lock)screen.orientation.lock('portrait-primary').catch(()=>{})}catch(e){}}
document.addEventListener('pointerdown',tryPortrait,{once:true});

function renderTraining(){
 const wo=P[S.day];
 let h=`<div class="days">${[1,2,3,4,5].map(d=>`<button class="day ${S.day===d?'on':''}" onclick="S.day=${d};save();render()">${DN[d]}</button>`).join('')}</div><h1>${wo.n}</h1><div class="note">${wo.note}${wo.mma?' · ВЕЧЕРОМ MMA':''}</div>`;
 wo.ex.forEach(ex=>{const sets=getSets(ex);h+=`<div class="card"><div class="exhead"><div><div class="exname">${ex.n}</div><div class="meta">${ex.s} × ${ex.time?ex.min+'–'+ex.max+' сек':ex.min+'–'+ex.max} · RIR ${ex.r} · отдых ${fmtTime(ex.rest)}</div></div><div class="tools"><button class="mini" onclick="S.hint=S.hint==='${ex.id}'?null:'${ex.id}';render()">?</button>${ex.v?`<button class="mini" onclick="window.open('${ex.v}','_blank')">▶</button>`:''}</div></div>${S.hint===ex.id?`<div class="hint">${ex.h}</div>`:''}`;
 sets.forEach((sd,i)=>{h+=`<div class="set"><span>S${i+1}</span>${ex.band?`<select onchange="setField(P[${S.day}].ex.find(x=>x.id==='${ex.id}'),${i},'load',this.value)"><option value="">резинка</option>${BANDS.map(b=>`<option ${sd.load===b?'selected':''}>${b}</option>`).join('')}</select>`:`<input inputmode="decimal" placeholder="кг" value="${sd.load}" onchange="setField(P[${S.day}].ex.find(x=>x.id==='${ex.id}'),${i},'load',this.value)">`}<input inputmode="numeric" placeholder="${ex.time?'сек':'повт'}" value="${sd.reps}" onchange="setField(P[${S.day}].ex.find(x=>x.id==='${ex.id}'),${i},'reps',this.value)"><select onchange="setField(P[${S.day}].ex.find(x=>x.id==='${ex.id}'),${i},'rir',this.value)">${['0','1','2','3+'].map(v=>`<option ${String(sd.rir)===v?'selected':''}>${v}</option>`).join('')}</select><button class="check ${sd.done?'on':''}" onclick="toggleSet(P[${S.day}].ex.find(x=>x.id==='${ex.id}'),${i})">✓</button></div>`});
 if(progression(ex))h+=`<div class="rec">↑ ГОТОВ К УВЕЛИЧЕНИЮ НАГРУЗКИ НА СЛЕДУЮЩЕЙ ТРЕНИРОВКЕ</div>`;
 h+=`<div class="tmr-row"><button class="tmr-start" onclick="startTimer(${ex.rest},'${ex.n.replace(/'/g,"\\'")}')">⏱ ${fmtTime(ex.rest)}</button></div></div>`});
 return h
}

function renderNutrition(){const goal=calcMacros(),t=totals(),pct=(v,g)=>Math.min(100,Math.round(v/g*100));let h=`<h1>ПИТАНИЕ</h1><div class="note">Точный рацион и цели скорректируем отдельно.</div><div class="card"><div class="macros">${[['ККАЛ',t.cal,goal.cal],['Б',t.p,goal.p],['Ж',t.f,goal.f],['У',t.c,goal.c]].map(([n,v,g])=>`<div class="macro"><b>${v}</b><small>${n} / ${g}</small><div class="progressbar"><i style="width:${pct(v,g)}%"></i></div></div>`).join('')}</div></div><div class="card"><b>ПАРАМЕТРЫ ТЕЛА</b><div class="grid3"><label>Вес<input value="${S.profile.weight}" onchange="S.profile.weight=this.value;save();render()"></label><label>Рост<input value="${S.profile.height}" onchange="S.profile.height=this.value;save();render()"></label><label>Возраст<input value="${S.profile.age}" onchange="S.profile.age=this.value;save();render()"></label></div><div class="grid2"><label>Активность<select onchange="S.profile.activity=this.value;save();render()">${[[1.2,'Низкая'],[1.375,'Лёгкая'],[1.55,'Средняя'],[1.725,'Высокая'],[1.9,'Очень высокая']].map(([v,n])=>`<option value="${v}" ${String(S.profile.activity)===String(v)?'selected':''}>${n}</option>`).join('')}</select></label><label>Цель<select onchange="S.profile.goal=this.value;save();render()">${[[-300,'Снижение'],[0,'Поддержание'],[300,'Набор']].map(([v,n])=>`<option value="${v}" ${String(S.profile.goal)===String(v)?'selected':''}>${n}</option>`).join('')}</select></label></div></div><div class="card"><b>ДОБАВИТЬ ПРОДУКТ</b><input placeholder="Поиск" value="${S.foodSearch}" oninput="S.foodSearch=this.value;render()"><div>${S.foods.filter(f=>f.name.toLowerCase().includes(S.foodSearch.toLowerCase())).slice(0,12).map(f=>`<div class="food"><div><b>${f.name}</b><br><small>${f.cal} ккал · Б ${f.p} · Ж ${f.f} · У ${f.c} / 100 г</small></div><button class="mini" onclick="const g=prompt('Сколько грамм?','100');if(g)addFood('${f.id}',g)">+</button></div>`).join('')}</div><button class="btn" onclick="S.foodForm={name:'',cal:'',p:'',f:'',c:''};render()">+ СВОЙ ПРОДУКТ</button></div>`;
 if(S.foodForm)h+=`<div class="card"><b>СВОЙ ПРОДУКТ / 100 Г</b><div class="grid2"><input placeholder="Название" oninput="S.foodForm.name=this.value"><input placeholder="ккал" inputmode="decimal" oninput="S.foodForm.cal=this.value"><input placeholder="белок" inputmode="decimal" oninput="S.foodForm.p=this.value"><input placeholder="жир" inputmode="decimal" oninput="S.foodForm.f=this.value"><input placeholder="углеводы" inputmode="decimal" oninput="S.foodForm.c=this.value"></div><div class="row"><button class="btn primary" onclick="addCustomFood()">СОХРАНИТЬ</button><button class="btn" onclick="S.foodForm=null;render()">ОТМЕНА</button></div></div>`;
 h+=`<div class="card"><b>СЕГОДНЯ</b>${dayFood().length?dayFood().map(x=>`<div class="food"><div><b>${x.name} · ${x.g} г</b><br><small>${x.cal} ккал · Б ${x.p} · Ж ${x.f} · У ${x.c}</small></div><button class="mini danger" onclick="delFood(${x.id})">×</button></div>`).join(''):'<div class="empty">Пока ничего не добавлено</div>'}</div><div class="row"><button class="btn" onclick="exportData()">💾 БЭКАП</button><button class="btn" onclick="importData()">📂 ЗАГРУЗИТЬ</button></div>`;return h}

function render(){const n=new Date(),clk=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0');document.getElementById('app').innerHTML=timerOverlay()+`<div class="top"><div class="bar"><div><div class="brand">MAX TIME</div><div class="sub">v2 · СИЛА + MMA</div></div><div class="clock">${clk}</div></div><div class="tabs">${[['training','ТРЕНИРОВКИ'],['nutrition','ПИТАНИЕ']].map(([k,n])=>`<button class="tab ${S.tab===k?'on':''}" onclick="S.tab='${k}';save();render()">${n}</button>`).join('')}</div></div><main>${S.tab==='nutrition'?renderNutrition():renderTraining()}</main>`}
load();if(!['training','nutrition'].includes(S.tab))S.tab='training';tryPortrait();render();setInterval(()=>{const e=document.querySelector('.clock');if(e){const n=new Date();e.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')}},10000);
