// MAX TIME v2 — original v1 timer audio + stable completion + previous workout values
(function(){
  let audioCtx=null,gongBuffer=null,countdownTimers=[];
  const OLD_GONG_KEY='max_time_original_gong_b64',OLD_SOURCE='https://raw.githubusercontent.com/SayanovVG/Time/backup-pre-max-time-v2-2026-08-23/index.html';
  function getAudioCtx(){try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch(e){return null}}
  async function getOriginalGongBase64(){let saved='';try{saved=localStorage.getItem(OLD_GONG_KEY)||''}catch(e){}if(saved)return saved;try{const r=await fetch(OLD_SOURCE,{cache:'no-store',mode:'cors'}),txt=await r.text(),m=txt.match(/const base64\s*=\s*'([^']+)'/);if(!m)return '';try{localStorage.setItem(OLD_GONG_KEY,m[1])}catch(e){}return m[1]}catch(e){return ''}}
  async function loadGong(){if(gongBuffer)return gongBuffer;const ctx=getAudioCtx();if(!ctx)return null;try{const b=await getOriginalGongBase64();if(!b)return null;const bin=atob(b),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return gongBuffer=await ctx.decodeAudioData(bytes.buffer.slice(0))}catch(e){return null}}
  async function playGong(){const ctx=getAudioCtx(),buffer=await loadGong();if(!ctx||!buffer)return;const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=buffer;g.gain.value=.8;s.connect(g);g.connect(ctx.destination);s.start(0);try{navigator.vibrate&&navigator.vibrate([250,100,350])}catch(e){}}
  function playBoxingBell(v=1){const ctx=getAudioCtx();if(!ctx)return;try{const now=ctx.currentTime;[{f:1050,a:.35,d:1.4},{f:2100,a:.18,d:1},{f:3150,a:.10,d:.7},{f:525,a:.12,d:1.2}].forEach(x=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=x.f;g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(x.a*v,now+.003);g.gain.exponentialRampToValueAtTime(.001,now+x.d);o.connect(g);g.connect(ctx.destination);o.start(now);o.stop(now+x.d+.05)})}catch(e){}}
  function clearCountdown(){countdownTimers.forEach(clearTimeout);countdownTimers=[]}function playCountdown(){clearCountdown();for(let i=0;i<10;i++)countdownTimers.push(setTimeout(()=>playBoxingBell(.25+i/9*.75),i*1000))}
  window.startTimer=function(sec,ex,eid){window.stopTimer(false);const seconds=Math.max(5,Number(sec)||60);S.timer={on:true,left:seconds,max:seconds,ex:ex||'',eid:eid??null,mod:false,saved:false,int:null};getAudioCtx();loadGong();S.timer.int=setInterval(()=>{if(!S.timer.on)return;S.timer.left--;if(S.timer.left===10)playCountdown();if(S.timer.left<=0){S.timer.left=0;clearInterval(S.timer.int);S.timer.int=null;clearCountdown();playGong();render();setTimeout(()=>{if(S.timer&&S.timer.left===0){S.timer={on:false,left:0,max:0,ex:'',eid:null,mod:false,saved:false,int:null};render()}},900);return}render()},1000);render()};
  window.stopTimer=function(close=true){clearCountdown();if(S.timer&&S.timer.int)clearInterval(S.timer.int);if(close!==false){S.timer={on:false,left:0,max:0,ex:'',eid:null,mod:false,saved:false,int:null};render()}};

  // History: each calendar day remains stored. New day starts from the latest previous result for that exercise.
  function keyDate(k){const m=String(k).match(/^(\d{4})-(\d{2})-(\d{2})_/);return m?m[1]+m[2]+m[3]:''}
  function prevSets(ex){const td=todayKey().replace(/-/g,''),suf='_'+ex.id,ks=Object.keys(S.train||{}).filter(k=>k.endsWith(suf)&&keyDate(k)&&keyDate(k)<td).sort();return ks.length?S.train[ks[ks.length-1]]:null}
  const baseGetSets=getSets;
  window.getSets=getSets=function(ex){const key=exKey(ex);if(!S.train[key]){const prev=prevSets(ex);S.train[key]=Array.from({length:ex.s},(_,i)=>({load:'',reps:'',rir:String(ex.r),done:false,prevLoad:prev&&prev[i]?prev[i].load:'',prevReps:prev&&prev[i]?prev[i].reps:'',prevRir:prev&&prev[i]?prev[i].rir:''}));save()}while(S.train[key].length<ex.s)S.train[key].push({load:'',reps:'',rir:String(ex.r),done:false});return S.train[key]};
  function completeSet(day,exId,i){const ex=P[day]&&P[day].ex.find(x=>x.id===exId);if(!ex)return;const sets=getSets(ex),s=sets[i];if(!s)return;const was=!!s.done;s.done=!was;if(!was){if(s.load===''&&s.prevLoad!=='')s.load=s.prevLoad;if(s.reps===''&&s.prevReps!=='')s.reps=s.prevReps;if(i<ex.s-1){const n=sets[i+1];if(s.load!=='')n.load=s.load;if(s.reps!=='')n.reps=s.reps;if(s.rir!==undefined)n.rir=s.rir}save();render();if(i<ex.s-1)window.startTimer(typeof gp==='function'?gp(ex.id,ex.rest):ex.rest,ex.n,ex.id);return}save();render()}
  window.toggleSet=completeSet;
  document.addEventListener('click',ev=>{const b=ev.target.closest&&ev.target.closest('button.check');if(!b)return;const m=(b.getAttribute('onclick')||'').match(/toggleSet\((\d+)\s*,\s*['\"]([^'\"]+)['\"]\s*,\s*(\d+)\)/);if(!m)return;ev.preventDefault();ev.stopImmediatePropagation();completeSet(+m[1],m[2],+m[3])},true);

  // Persist typing immediately; onchange alone can lose the last edit if the PWA is closed quickly.
  document.addEventListener('input',ev=>{const el=ev.target,row=el.closest&&el.closest('.set');if(!row)return;const b=row.querySelector('button.check'),m=b&&(b.getAttribute('onclick')||'').match(/toggleSet\((\d+)\s*,\s*['\"]([^'\"]+)['\"]\s*,\s*(\d+)\)/);if(!m)return;const ex=P[+m[1]].ex.find(x=>x.id===m[2]),s=getSets(ex)[+m[3]],els=row.querySelectorAll('input,select');if(!s)return;s.load=els[0]?els[0].value:s.load;s.reps=els[1]?els[1].value:s.reps;s.rir=els[2]?els[2].value:s.rir;save()},true);

  // Show previous workout values in grey as placeholders. Entered current values replace them.
  const oldRT=renderTraining;renderTraining=function(){let h=oldRT();const day=S.day;for(const ex of P[day].ex){const sets=getSets(ex);sets.forEach((s,i)=>{if(!s.prevLoad&&!s.prevReps)return;const needle=`onclick=\"toggleSet(${day},'${ex.id}',${i})\"`,p=h.indexOf(needle);if(p<0)return;const st=h.lastIndexOf('<div class="set">',p),en=h.indexOf('</div>',p);if(st<0||en<0)return;let ch=h.slice(st,en+6),prev=[s.prevLoad,s.prevReps].filter(Boolean).join(' / ');ch=ch.replace(`<span>S${i+1}</span>`,`<span>S${i+1}</span><small class="prev-set">было: ${prev}</small>`);h=h.slice(0,st)+ch+h.slice(en+6)});}return h};

  // Food search: preserve focus + online search.
  let fst=null,seq=0;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function box(i){let b=i.parentElement.querySelector('.food-search-results');if(!b){b=document.createElement('div');b.className='food-search-results';i.insertAdjacentElement('afterend',b)}return b}function locals(q){return(S.foods||[]).filter(f=>f.name.toLowerCase().includes(q.toLowerCase())).slice(0,8)}function row(f,on=false){return `<div class="food"><div><b>${esc(f.name)}</b><br><small>${Math.round(f.cal)} ккал · Б ${(+f.p||0).toFixed(1)} · Ж ${(+f.f||0).toFixed(1)} · У ${(+f.c||0).toFixed(1)} / 100 г${on?' · интернет':''}</small></div><button class="mini food-add-search" data-id="${esc(f.id||'')}" data-online="${on?1:0}" data-name="${esc(f.name)}" data-cal="${+f.cal||0}" data-p="${+f.p||0}" data-f="${+f.f||0}" data-c="${+f.c||0}">+</button></div>`}
  async function searchFood(i,q){const b=box(i),ls=locals(q);b.innerHTML=ls.map(x=>row(x)).join('')+(q.length>=2?'<div class="nutrition-rule">Ищу ещё в интернете…</div>':'');if(q.length<2)return;const s=++seq;try{const r=await fetch('https://world.openfoodfacts.org/cgi/search.pl?search_terms='+encodeURIComponent(q)+'&search_simple=1&action=process&json=1&page_size=8'),d=await r.json();if(s!==seq||i.value!==q)return;const os=(d.products||[]).map(p=>{const n=p.nutriments||{};return{name:p.product_name_ru||p.product_name||'',cal:+n['energy-kcal_100g']||0,p:+n.proteins_100g||0,f:+n.fat_100g||0,c:+n.carbohydrates_100g||0}}).filter(x=>x.name&&x.cal).slice(0,6);b.innerHTML=ls.map(x=>row(x)).join('')+(os.length?'<div class="nutrition-rule">ИЗ ИНТЕРНЕТА</div>'+os.map(x=>row(x,true)).join(''):'<div class="nutrition-rule">В интернете подходящих продуктов не найдено</div>')}catch(e){b.innerHTML=ls.map(x=>row(x)).join('')+'<div class="nutrition-rule">Интернет-поиск сейчас недоступен</div>'}}
  document.addEventListener('input',ev=>{const i=ev.target;if(!(i instanceof HTMLInputElement)||i.placeholder!=='Поиск')return;ev.stopImmediatePropagation();S.foodSearch=i.value;clearTimeout(fst);searchFood(i,i.value);fst=setTimeout(()=>searchFood(i,i.value),450)},true);
  document.addEventListener('click',ev=>{const b=ev.target.closest&&ev.target.closest('.food-add-search');if(!b)return;ev.preventDefault();const g=+prompt('Сколько грамм?','100');if(!g)return;if(b.dataset.online==='1'){const f={id:'net'+Date.now(),name:b.dataset.name,cal:+b.dataset.cal,p:+b.dataset.p,f:+b.dataset.f,c:+b.dataset.c};S.foods.push(f);dayFood().push({id:Date.now(),name:f.name,g,cal:Math.round(f.cal*g/100),p:+(f.p*g/100).toFixed(1),f:+(f.f*g/100).toFixed(1),c:+(f.c*g/100).toFixed(1)});save();render()}else addFood(b.dataset.id,g)},true);

  const st=document.createElement('style');st.textContent='.prev-set{display:block;grid-column:2/5;color:var(--dim);font-size:9px;opacity:.8;margin-top:-5px}';document.head.appendChild(st);
  function unlock(){getAudioCtx();loadGong()}window.addEventListener('pointerdown',unlock,{once:true});window.addEventListener('touchstart',unlock,{once:true,passive:true});
  window.tryPortrait=async function(){try{if(screen.orientation&&screen.orientation.lock)await screen.orientation.lock('portrait')}catch(e){}};tryPortrait();window.addEventListener('orientationchange',()=>setTimeout(tryPortrait,100));document.addEventListener('visibilitychange',()=>{if(!document.hidden)tryPortrait()});window.addEventListener('pageshow',tryPortrait);
})();