// MAX TIME v37 — analytics + Max coach
(function(){
  if(!S.measurements)S.measurements=[];
  if(!S.dailySummary)S.dailySummary={};
  const num=v=>{const x=parseFloat(String(v).replace(',','.'));return Number.isFinite(x)?x:null};
  const sortedMeasures=()=>S.measurements.slice().sort((a,b)=>a.date.localeCompare(b.date));
  function saveMetric(field,value){const v=num(value);if(v===null)return;let r=S.measurements.find(x=>x.date===todayKey());if(!r){r={date:todayKey()};S.measurements.push(r)}r[field]=v;S.profile[field]=v;S.measurements.sort((a,b)=>a.date.localeCompare(b.date));save();snapshot();render()}
  window.saveBodyMetric=saveMetric;
  function snapshot(){try{const t=totals(),g=calcMacros(),d=todayKey();S.dailySummary[d]={date:d,cal:+t.cal||0,p:+t.p||0,f:+t.f||0,c:+t.c||0,targetCal:+g.cal||0,targetP:+g.p||0,targetF:+g.f||0,targetC:+g.c||0,weight:num(S.profile.weight),waist:num(S.profile.waist)};localStorage.setItem('max_time_v2',JSON.stringify({...S,timer:{on:false,left:0,max:0,ex:'',eid:null,mod:false,saved:false}}))}catch(e){}}
  window.mtSnapshot=snapshot;document.addEventListener('change',()=>setTimeout(snapshot,50),true);window.addEventListener('pagehide',snapshot);document.addEventListener('visibilitychange',()=>{if(document.hidden)snapshot()});
  const oldRN=renderNutrition;renderNutrition=function(){let h=oldRN();return h.replace(/onchange="S\.profile\.weight=this\.value;save\(\);render\(\)"/g,"onchange=\"saveBodyMetric('weight',this.value)\"").replace(/onchange="S\.profile\.waist=this\.value;save\(\);render\(\)"/g,"onchange=\"saveBodyMetric('waist',this.value)\"")};
  function delta(field,days){const a=sortedMeasures().filter(x=>num(x[field])!==null);if(a.length<2)return null;const last=a[a.length-1],cut=new Date(last.date+'T12:00:00');cut.setDate(cut.getDate()-days);let first=a[0];for(const x of a){if(new Date(x.date+'T12:00:00')>=cut){first=x;break}}return +(num(last[field])-num(first[field])).toFixed(1)}
  function avg7(){const a=sortedMeasures().filter(x=>num(x.weight)!==null).slice(-7);return a.length?+(a.reduce((s,x)=>s+num(x.weight),0)/a.length).toFixed(1):null}
  function nutrition7(){const a=Object.values(S.dailySummary||{}).sort((a,b)=>a.date.localeCompare(b.date)).slice(-7);if(!a.length)return null;return{days:a.length,cal:Math.round(a.reduce((s,x)=>s+(+x.cal||0),0)/a.length),target:Math.round(a.reduce((s,x)=>s+(+x.targetCal||0),0)/a.length),p:Math.round(a.reduce((s,x)=>s+(+x.p||0),0)/a.length)}}
  function trainStats(){const dates=new Set(),done=[];Object.entries(S.train||{}).forEach(([k,sets])=>{const d=k.slice(0,10),c=(sets||[]).filter(x=>x.done);if(c.length){dates.add(d);done.push(...c)}});return{days:dates.size,sets:done.length}}
  function coachData(){return{profile:{weight:num(S.profile.weight),waist:num(S.profile.waist),height:num(S.profile.height),goal:'recomposition',mma:'Mon/Wed/Fri 19:00-20:00'},measurements:sortedMeasures().slice(-60),nutrition:Object.values(S.dailySummary||{}).sort((a,b)=>a.date.localeCompare(b.date)).slice(-30),training:Object.entries(S.train||{}).filter(([,sets])=>(sets||[]).some(s=>s.done)).slice(-120).map(([key,sets])=>({key,sets})),program:P}}
  window.askMaxCoach=async function(){const q=document.getElementById('max-q'),out=document.getElementById('max-answer'),btn=document.getElementById('max-send');if(!q||!q.value.trim())return;out.textContent='Анализирую данные…';btn.disabled=true;try{const r=await fetch('/api/max-coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q.value.trim(),data:coachData()})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Сервис недоступен');out.textContent=j.answer||'Ответ не получен'}catch(e){out.textContent='ИИ-сервис пока не подключён к текущему хостингу. Интерфейс и передача данных готовы; нужен серверный endpoint с API-ключом.'}finally{btn.disabled=false}};
  function renderAnalytics(){const m=sortedMeasures(),last=m[m.length-1]||{},nw=nutrition7(),ts=trainStats(),dw=delta('weight',28),dwa=delta('waist',28);return `<h1>АНАЛИТИКА</h1><div class="note">История тренировок, питания, веса и талии сохраняется по датам.</div><div class="card"><b>ТЕКУЩИЙ СТАТУС</b><div class="analytics-kpis"><span><strong>${last.weight??S.profile.weight??'—'}</strong><small>вес, кг</small></span><span><strong>${avg7()??'—'}</strong><small>средний 7 дн.</small></span><span><strong>${last.waist??S.profile.waist??'—'}</strong><small>талия, см</small></span><span><strong>${ts.sets}</strong><small>подходов</small></span></div><div class="analytics-note">28 дней: вес ${dw===null?'—':(dw>0?'+':'')+dw+' кг'} · талия ${dwa===null?'—':(dwa>0?'+':'')+dwa+' см'}</div></div><div class="card"><b>ПИТАНИЕ · 7 ДНЕЙ</b>${nw?`<div class="analytics-kpis three"><span><strong>${nw.cal}</strong><small>ккал/день</small></span><span><strong>${nw.target}</strong><small>цель</small></span><span><strong>${nw.p}</strong><small>белок</small></span></div><div class="nutrition-rule">Заполнено ${nw.days}/7 дней</div>`:'<div class="analytics-empty">Пока нет истории</div>'}</div><div class="card"><b>ТРЕНИРОВКИ</b><div class="nutrition-rule">Тренировочных дней: ${ts.days} · выполненных подходов: ${ts.sets}</div></div><div class="card"><b>ИСТОРИЯ ЗАМЕРОВ</b>${m.length?m.slice(-10).reverse().map(x=>`<div class="analytics-row"><span>${x.date}</span><strong>${x.weight??'—'} кг · ${x.waist??'—'} см</strong></div>`).join(''):'<div class="analytics-empty">Пока нет замеров</div>'}</div><div class="card max-coach"><b>МАКС — ТРЕНЕР</b><div class="nutrition-rule">Макс получает историю MAX TIME и анализирует тренировки, питание, вес и талию.</div><textarea id="max-q" placeholder="Например: как идёт мой прогресс и что нужно изменить?"></textarea><button id="max-send" class="btn primary" onclick="askMaxCoach()">СПРОСИТЬ МАКСА</button><div id="max-answer" class="max-answer"></div></div>`}
  const baseRender=render;render=function(){baseRender();const tabs=document.querySelector('.tabs');if(tabs&&!tabs.querySelector('[data-analytics]')){const b=document.createElement('button');b.className='tab '+(S.tab==='analytics'?'on':'');b.dataset.analytics='1';b.textContent='АНАЛИТИКА';b.onclick=()=>{S.tab='analytics';save();render()};tabs.appendChild(b)}if(S.tab==='analytics'){const main=document.querySelector('main');if(main)main.innerHTML=renderAnalytics();document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));const a=document.querySelector('[data-analytics]');if(a)a.classList.add('on')}};
  const st=document.createElement('style');st.textContent=`.tabs{overflow-x:auto}.tab{min-width:max-content}.analytics-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.analytics-kpis.three{grid-template-columns:repeat(3,1fr)}.analytics-kpis span{background:#10141a;border:1px solid var(--line);border-radius:12px;padding:10px 5px;text-align:center}.analytics-kpis strong{display:block;font-size:19px}.analytics-kpis small{display:block;font-size:9px;color:var(--mut)}.analytics-note,.analytics-empty{font-size:11px;color:var(--mut);margin-top:12px}.analytics-row{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.055);font-size:12px}.max-coach textarea{width:100%;min-height:96px;margin:12px 0;background:#10141a;color:var(--txt);border:1px solid var(--line);border-radius:12px;padding:12px;font:inherit;resize:vertical}.max-answer{white-space:pre-wrap;margin-top:12px;font-size:12px;line-height:1.55;color:#d9dee5}.max-coach .btn{width:100%}@media(max-width:420px){.analytics-kpis{grid-template-columns:repeat(2,1fr)}.analytics-kpis.three{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(st);
  if(!localStorage.getItem('mt_measure_seed_v37')){S.measurements.push({date:todayKey(),weight:num(S.profile.weight),waist:num(S.profile.waist)});localStorage.setItem('mt_measure_seed_v37','1');save()}
  snapshot();render();
})();