// MAX TIME v38 — local analytics + report for ChatGPT
(function(){
  if(!S.measurements)S.measurements=[];
  if(!S.dailySummary)S.dailySummary={};
  if(!S.analyticsPeriod)S.analyticsPeriod=28;
  const num=v=>{const x=parseFloat(String(v??'').replace(',','.'));return Number.isFinite(x)?x:null};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const measures=()=>S.measurements.slice().sort((a,b)=>a.date.localeCompare(b.date));
  const dateMs=d=>new Date(d+'T12:00:00').getTime();
  const cutoff=days=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-days+1);return d.getTime()};
  const inPeriod=(date,days)=>dateMs(date)>=cutoff(days);

  function saveMetric(field,value){const v=num(value);if(v===null)return;let r=S.measurements.find(x=>x.date===todayKey());if(!r){r={date:todayKey()};S.measurements.push(r)}r[field]=v;S.profile[field]=v;S.measurements.sort((a,b)=>a.date.localeCompare(b.date));save();snapshot();render()}
  window.saveBodyMetric=saveMetric;

  function snapshot(){try{const t=totals(),g=calcMacros(),d=todayKey();S.dailySummary[d]={date:d,cal:+t.cal||0,p:+t.p||0,f:+t.f||0,c:+t.c||0,targetCal:+g.cal||0,targetP:+g.p||0,targetF:+g.f||0,targetC:+g.c||0,weight:num(S.profile.weight),waist:num(S.profile.waist)};localStorage.setItem('max_time_v2',JSON.stringify({...S,timer:{on:false,left:0,max:0,ex:'',eid:null,mod:false,saved:false}}))}catch(e){}}
  window.mtSnapshot=snapshot;
  document.addEventListener('change',()=>setTimeout(snapshot,50),true);
  window.addEventListener('pagehide',snapshot);
  document.addEventListener('visibilitychange',()=>{if(document.hidden)snapshot()});

  const oldRN=renderNutrition;
  renderNutrition=function(){let h=oldRN();return h.replace(/onchange="S\.profile\.weight=this\.value;save\(\);render\(\)"/g,"onchange=\"saveBodyMetric('weight',this.value)\"").replace(/onchange="S\.profile\.waist=this\.value;save\(\);render\(\)"/g,"onchange=\"saveBodyMetric('waist',this.value)\"")};

  function metricStats(field,days){const a=measures().filter(x=>num(x[field])!==null&&inPeriod(x.date,days));if(!a.length)return{count:0,last:null,first:null,delta:null,avg:null};const vals=a.map(x=>num(x[field]));return{count:a.length,last:vals.at(-1),first:vals[0],delta:a.length>1?+(vals.at(-1)-vals[0]).toFixed(1):null,avg:+(vals.reduce((s,v)=>s+v,0)/vals.length).toFixed(1)}}
  function weightAvg7(){const a=measures().filter(x=>num(x.weight)!==null).slice(-7);return a.length?+(a.reduce((s,x)=>s+num(x.weight),0)/a.length).toFixed(1):null}
  function nutritionStats(days){const a=Object.values(S.dailySummary||{}).filter(x=>x&&x.date&&inPeriod(x.date,days)).sort((a,b)=>a.date.localeCompare(b.date));if(!a.length)return null;const avg=k=>Math.round(a.reduce((s,x)=>s+(+x[k]||0),0)/a.length);const compliance=a.filter(x=>+x.targetCal>0&&Math.abs((+x.cal||0)-(+x.targetCal||0))<=Math.max(150,+x.targetCal*.08)).length;const proteinOk=a.filter(x=>+x.targetP>0&&(+x.p||0)>=+x.targetP*.9).length;return{days:a.length,cal:avg('cal'),target:avg('targetCal'),p:avg('p'),targetP:avg('targetP'),f:avg('f'),c:avg('c'),calCompliance:Math.round(compliance/a.length*100),proteinCompliance:Math.round(proteinOk/a.length*100)}}

  function allExercises(){const out={};for(let d=1;d<=5;d++)for(const ex of P[d].ex)out[ex.id]=ex;return out}
  const EX=allExercises();
  function sessionScore(ex,sets){const done=(sets||[]).filter(s=>s.done);if(!done.length)return null;const reps=done.reduce((s,x)=>s+(num(x.reps)||0),0);const avgRir=done.reduce((s,x)=>s+(parseInt(x.rir)||0),0)/done.length;const numericLoads=done.map(x=>num(x.load)).filter(v=>v!==null);const volume=numericLoads.length===done.length?done.reduce((s,x)=>s+(num(x.load)||0)*(num(x.reps)||0),0):null;return{reps,avgRir:+avgRir.toFixed(1),volume,sets:done.length,load:numericLoads.length?Math.max(...numericLoads):null}}
  function exerciseTrends(days){const by={};Object.entries(S.train||{}).forEach(([key,sets])=>{const date=key.slice(0,10);if(!inPeriod(date,days))return;const id=key.slice(11),ex=EX[id];if(!ex)return;const score=sessionScore(ex,sets);if(!score)return;(by[id]||(by[id]=[])).push({date,score})});const rows=[];for(const [id,a] of Object.entries(by)){a.sort((x,y)=>x.date.localeCompare(y.date));const ex=EX[id],first=a[0].score,last=a.at(-1).score;let pct=null,kind='reps';if(first.volume&&last.volume){pct=Math.round((last.volume-first.volume)/first.volume*100);kind='volume'}else if(first.reps>0){pct=Math.round((last.reps-first.reps)/first.reps*100)}rows.push({id,name:ex.n,sessions:a.length,pct,kind,last,first,stalled:a.length>=3&&pct!==null&&pct<=2})}return rows.sort((a,b)=>b.sessions-a.sessions)}
  function trainingStats(days){const dates=new Set();let sets=0;Object.entries(S.train||{}).forEach(([k,a])=>{const d=k.slice(0,10);if(!inPeriod(d,days))return;const c=(a||[]).filter(x=>x.done).length;if(c){dates.add(d);sets+=c}});const trends=exerciseTrends(days);return{days:dates.size,sets,trends,progressing:trends.filter(x=>x.sessions>=2&&x.pct!==null&&x.pct>=5),stalled:trends.filter(x=>x.stalled)}}

  function localConclusions(days){const w=metricStats('weight',days),wa=metricStats('waist',days),n=nutritionStats(days),t=trainingStats(days),out=[];
    if(w.count<2||wa.count<2)out.push({type:'info',title:'Пока мало замеров',text:'Для уверенного вывода нужны хотя бы 2 замера веса и талии, а лучше 2–4 недели регулярных данных.'});
    if(w.delta!==null&&wa.delta!==null){
      if(wa.delta<=-1&&Math.abs(w.delta)<=1.5)out.push({type:'good',title:'Рекомпозиция идёт в нужную сторону',text:`Талия ${wa.delta} см, вес ${w.delta>0?'+':''}${w.delta} кг. Калорийность пока менять не нужно.`});
      else if(wa.delta>1&&w.delta>1)out.push({type:'warn',title:'Вес и талия растут вместе',text:'Если этот тренд держится не меньше 10–14 дней, калорийность вероятно завышена.'});
      else if(w.delta<-1.5&&days<=28)out.push({type:'warn',title:'Вес снижается быстро',text:'Проверь силовые и самочувствие. Если они ухудшаются, дефицит слишком большой.'});
      else out.push({type:'info',title:'Выраженного сигнала по составу тела пока нет',text:'Не меняй калории по одному колебанию веса. Смотрим одновременно на талию, средний вес и силовые.'});
    }
    if(n){if(n.proteinCompliance>=80)out.push({type:'good',title:'Белок держится стабильно',text:`Цель по белку выполнена примерно в ${n.proteinCompliance}% заполненных дней.`});else if(n.days>=5)out.push({type:'warn',title:'Белок часто ниже цели',text:`Цель выполнена примерно в ${n.proteinCompliance}% заполненных дней. Это стоит исправить раньше, чем менять программу.`});if(n.calCompliance<60&&n.days>=5)out.push({type:'warn',title:'Калорийность нестабильна',text:`В целевой диапазон попало около ${n.calCompliance}% заполненных дней. При таком разбросе сложнее оценивать реакцию организма.`})}
    if(t.progressing.length)out.push({type:'good',title:'Есть силовой прогресс',text:`Растут: ${t.progressing.slice(0,3).map(x=>x.name).join(', ')}${t.progressing.length>3?' и другие':''}.`});
    if(t.stalled.length)out.push({type:'warn',title:'Есть возможное плато',text:`Без заметного роста за ${days} дней: ${t.stalled.slice(0,3).map(x=>x.name).join(', ')}. Сначала проверяем технику, RIR и восстановление, а не сразу меняем упражнение.`});
    if(!out.length)out.push({type:'info',title:'Собираем данные',text:'Продолжай отмечать подходы, питание, вес и талию. Аналитика станет точнее по мере накопления истории.'});
    return out.slice(0,6)
  }

  function spark(field,days){const a=measures().filter(x=>num(x[field])!==null&&inPeriod(x.date,days));if(a.length<2)return '<div class="analytics-empty">Нужно минимум 2 замера</div>';const vals=a.map(x=>num(x[field])),w=300,h=70,min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,pts=vals.map((v,i)=>`${i/(vals.length-1)*w},${h-8-(v-min)/range*(h-16)}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="3" vector-effect="non-scaling-stroke"/></svg>`}

  function report(days){const w=metricStats('weight',days),wa=metricStats('waist',days),n=nutritionStats(days),t=trainingStats(days),m=measures().filter(x=>inPeriod(x.date,days));let lines=[`MAX TIME — отчёт за ${days} дней`,`Цель: рекомпозиция. MMA: Пн/Ср/Пт 19:00–20:00.`,``,`ЗАМЕРЫ`,`Вес: сейчас ${w.last??'нет данных'} кг; среднее 7 дней ${weightAvg7()??'нет данных'} кг; изменение за период ${w.delta===null?'нет данных':(w.delta>0?'+':'')+w.delta+' кг'}.`,`Талия: сейчас ${wa.last??'нет данных'} см; изменение за период ${wa.delta===null?'нет данных':(wa.delta>0?'+':'')+wa.delta+' см'}.`];
    if(n)lines.push('',`ПИТАНИЕ`,`Заполнено дней: ${n.days}/${days}. Среднее: ${n.cal} ккал (цель ${n.target}), Б ${n.p} г (цель ${n.targetP}), Ж ${n.f} г, У ${n.c} г.`,`Попадание в калорийность: ${n.calCompliance}%. Белок ≥90% цели: ${n.proteinCompliance}%.`);else lines.push('','ПИТАНИЕ','Нет сохранённых данных за период.');
    lines.push('',`ТРЕНИРОВКИ`,`Тренировочных дней: ${t.days}. Выполненных рабочих подходов: ${t.sets}.`);
    const tr=t.trends.filter(x=>x.sessions>=2).slice(0,12);if(tr.length){lines.push('Динамика упражнений:');tr.forEach(x=>lines.push(`- ${x.name}: ${x.sessions} тренировок; ${x.pct===null?'динамика не рассчитана':(x.pct>0?'+':'')+x.pct+'% по '+(x.kind==='volume'?'объёму нагрузки':'повторениям')}; последний RIR ~${x.last.avgRir}.`))}else lines.push('Недостаточно повторных тренировок для сравнения упражнений.');
    if(m.length){lines.push('','ПОСЛЕДНИЕ ЗАМЕРЫ');m.slice(-10).forEach(x=>lines.push(`- ${x.date}: вес ${x.weight??'—'} кг, талия ${x.waist??'—'} см`))}
    lines.push('','ЛОКАЛЬНЫЕ ВЫВОДЫ MAX TIME');localConclusions(days).forEach(x=>lines.push(`- ${x.title}: ${x.text}`));lines.push('','Проанализируй эти данные как мой тренер: оцени рекомпозицию, прогресс силовых, питание, восстановление с учётом MMA и скажи, что оставить, что изменить и на что обратить внимание.');return lines.join('\n')
  }
  window.setAnalyticsPeriod=function(d){S.analyticsPeriod=+d;save();render()};
  window.copyMaxReport=async function(){const text=report(S.analyticsPeriod||28);let ok=false;try{await navigator.clipboard.writeText(text);ok=true}catch(e){try{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();ok=document.execCommand('copy');ta.remove()}catch(_){} }const b=document.getElementById('copy-report');if(b){const old=b.textContent;b.textContent=ok?'✓ СКОПИРОВАНО':'НЕ УДАЛОСЬ СКОПИРОВАТЬ';setTimeout(()=>{b.textContent=old},1800)}};
  window.previewMaxReport=function(){const box=document.getElementById('report-preview');if(box){box.textContent=report(S.analyticsPeriod||28);box.hidden=!box.hidden}};

  function renderAnalytics(){const days=S.analyticsPeriod||28,w=metricStats('weight',days),wa=metricStats('waist',days),n=nutritionStats(days),t=trainingStats(days),cons=localConclusions(days),tr=t.trends.filter(x=>x.sessions>=2).slice(0,8);return `<h1>АНАЛИТИКА</h1><div class="note">Всё считается прямо на телефоне. Данные никуда не отправляются.</div><div class="periods">${[7,14,28].map(d=>`<button class="period ${days===d?'on':''}" onclick="setAnalyticsPeriod(${d})">${d} ДНЕЙ</button>`).join('')}</div><div class="card"><b>ТЕКУЩИЙ СТАТУС</b><div class="analytics-kpis"><span><strong>${w.last??S.profile.weight??'—'}</strong><small>вес, кг</small></span><span><strong>${weightAvg7()??'—'}</strong><small>средний 7 дн.</small></span><span><strong>${wa.last??S.profile.waist??'—'}</strong><small>талия, см</small></span><span><strong>${t.sets}</strong><small>подходов</small></span></div></div><div class="card"><b>ВЕС · ${days} ДНЕЙ</b><div class="analytics-note">Изменение: ${w.delta===null?'недостаточно данных':(w.delta>0?'+':'')+w.delta+' кг'}</div>${spark('weight',days)}</div><div class="card"><b>ТАЛИЯ · ${days} ДНЕЙ</b><div class="analytics-note">Изменение: ${wa.delta===null?'недостаточно данных':(wa.delta>0?'+':'')+wa.delta+' см'}</div>${spark('waist',days)}</div><div class="card"><b>ПИТАНИЕ</b>${n?`<div class="analytics-kpis three"><span><strong>${n.cal}</strong><small>ккал/день</small></span><span><strong>${n.p}</strong><small>белок/день</small></span><span><strong>${n.calCompliance}%</strong><small>в цели ккал</small></span></div><div class="nutrition-rule">Заполнено ${n.days}/${days} дней · белок ≥90% цели: ${n.proteinCompliance}%</div>`:'<div class="analytics-empty">Нет сохранённой истории питания за период</div>'}</div><div class="card"><b>ТРЕНИРОВКИ</b><div class="nutrition-rule">Тренировочных дней: ${t.days} · выполненных подходов: ${t.sets}</div>${tr.length?tr.map(x=>`<div class="analytics-row"><span>${esc(x.name)}<small>${x.sessions} тренировок · RIR ${x.last.avgRir}</small></span><strong class="${x.pct!==null&&x.pct>=5?'pos':x.stalled?'neg':''}">${x.pct===null?'—':(x.pct>0?'+':'')+x.pct+'%'}</strong></div>`).join(''):'<div class="analytics-empty">Нужно минимум 2 тренировки одного упражнения для сравнения</div>'}</div><div class="card conclusions"><b>ВЫВОДЫ MAX TIME</b>${cons.map(x=>`<div class="conclusion ${x.type}"><strong>${esc(x.title)}</strong><span>${esc(x.text)}</span></div>`).join('')}</div><div class="card report-card"><b>ОТЧЁТ ДЛЯ МАКСА</b><div class="nutrition-rule">Приложение подготовит только спортивные данные за выбранный период. Ничего не отправляется автоматически: текст просто копируется в буфер, после чего вставь его в наш чат.</div><button id="copy-report" class="btn primary" onclick="copyMaxReport()">СКОПИРОВАТЬ ОТЧЁТ ДЛЯ МАКСА</button><button class="btn" onclick="previewMaxReport()">ПОКАЗАТЬ ОТЧЁТ</button><pre id="report-preview" class="report-preview" hidden></pre></div>`}

  const baseRender=render;
  render=function(){baseRender();const tabs=document.querySelector('.tabs');if(tabs&&!tabs.querySelector('[data-analytics]')){const b=document.createElement('button');b.className='tab '+(S.tab==='analytics'?'on':'');b.dataset.analytics='1';b.textContent='АНАЛИТИКА';b.onclick=()=>{S.tab='analytics';save();render()};tabs.appendChild(b)}if(S.tab==='analytics'){const main=document.querySelector('main');if(main)main.innerHTML=renderAnalytics();document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));const a=document.querySelector('[data-analytics]');if(a)a.classList.add('on')}};

  const st=document.createElement('style');st.textContent=`.tabs{overflow-x:auto}.tab{min-width:max-content}.periods{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:14px 0}.period{padding:9px 6px;border-radius:10px;background:var(--bg2);border:1px solid var(--line);color:var(--mut);font:inherit;font-size:11px;font-weight:800}.period.on{background:var(--a);border-color:var(--a);color:#111}.analytics-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.analytics-kpis.three{grid-template-columns:repeat(3,1fr)}.analytics-kpis span{background:#10141a;border:1px solid var(--line);border-radius:12px;padding:10px 5px;text-align:center}.analytics-kpis strong{display:block;font-size:19px}.analytics-kpis small{display:block;font-size:9px;color:var(--mut)}.analytics-note,.analytics-empty{font-size:11px;color:var(--mut);margin-top:10px}.spark{width:100%;height:76px;color:var(--a);margin-top:8px}.analytics-row{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.055);font-size:12px}.analytics-row:last-child{border-bottom:none}.analytics-row span small{display:block;color:var(--mut);font-size:9px;margin-top:2px}.analytics-row strong{font-size:12px}.analytics-row .pos{color:var(--ok)}.analytics-row .neg{color:var(--danger)}.conclusion{padding:11px 12px;border-radius:11px;margin-top:9px;border:1px solid var(--line);background:#10141a}.conclusion strong,.conclusion span{display:block}.conclusion strong{font-size:12px}.conclusion span{font-size:11px;color:var(--mut);line-height:1.5;margin-top:4px}.conclusion.good{border-left:3px solid var(--ok)}.conclusion.warn{border-left:3px solid var(--danger)}.conclusion.info{border-left:3px solid var(--a)}.report-card .btn{width:100%;margin-top:10px}.report-preview{white-space:pre-wrap;word-break:break-word;background:#10141a;border:1px solid var(--line);border-radius:11px;padding:12px;margin-top:10px;color:var(--mut);font:500 10px/1.5 Manrope,sans-serif;max-height:360px;overflow:auto}@media(max-width:420px){.analytics-kpis{grid-template-columns:repeat(2,1fr)}.analytics-kpis.three{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(st);

  if(!localStorage.getItem('mt_measure_seed_v38')){if(!S.measurements.some(x=>x.date===todayKey()))S.measurements.push({date:todayKey(),weight:num(S.profile.weight),waist:num(S.profile.waist)});localStorage.setItem('mt_measure_seed_v38','1');save()}
  snapshot();render();
})();