import { useState, type CSSProperties } from 'react';
import { ChevronLeft, ChevronRight, Plus, CalendarDays } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { DAYS, dayKey, formatDay, monthGrid, monthStart, shiftMonth, shiftDay, weekDays, parseDay, timeMinutes, durationLabel, type TaskRow, type Project } from './lib/model';
export function CalendarView({ date, choose, tasks, edit, add }: { date: string; choose:(day:string)=>void; tasks:TaskRow[]; edit:(row:TaskRow)=>void; add:(date:string,time?:string)=>void }) {
  const [month,setMonth] = useState(monthStart(date)), [view,setView] = useState('month');
  const today = dayKey(), days = view==='month' ? monthGrid(month) : weekDays(date);
  const move = (delta:number) => { if(view==='month')setMonth(shiftMonth(month,delta));else choose(shiftDay(date,delta*7)); };
  return <section className="d-calendar-view"><div className="d-calendar-toolbar"><h2>{formatDay(view==='month' ? month : date,{month:'long',year:'numeric'}).replace(' г.','')}</h2><div className="d-calendar-controls"><button className="d-icon" aria-label="Назад по календарю" disabled={(view==='month'?month:date)<='2000-01-01'} onClick={()=>move(-1)}><ChevronLeft/></button><button className="d-secondary" onClick={()=>{choose(today);setMonth(monthStart(today));}}>Сегодня</button><button className="d-icon" aria-label="Вперёд по календарю" disabled={(view==='month'?month:date)>='2199-11-01'} onClick={()=>move(1)}><ChevronRight/></button></div></div><Tabs value={view} onValueChange={setView}><TabsList className="d-tabs"><TabsTrigger value="month">Месяц</TabsTrigger><TabsTrigger value="week">7 дней</TabsTrigger></TabsList></Tabs>
  <div className={`d-month-grid ${view==='week'?'d-week-grid':''}`}>{DAYS.map(d=><div key={d} className="d-weekday">{d}</div>)}{days.map(day=>{const list=tasks.filter(r=>r.body.date===day).sort((a,b)=>(a.body.time||'99').localeCompare(b.body.time||'99'));return <div key={day} className={`d-calendar-cell ${day===date?'selected':''} ${day===today?'today':''} ${day.slice(0,7)!==month.slice(0,7)&&view==='month'?'muted':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/den-task');const row=tasks.find(r=>r.id===id);if(row)edit({...row,body:{...row.body,date:day}});}}><button className="d-cell-date" onClick={()=>choose(day)} aria-label={formatDay(day,{day:'numeric',month:'long',year:'numeric'})} aria-pressed={date===day}><span className="d-cell-weekday">{DAYS[(parseDay(day).getDay()+6)%7]} </span><span>{parseDay(day).getDate()}</span><small>{list.length||''}</small></button><div className="d-cell-tasks">{list.slice(0,view==='week'?8:3).map(row=><button key={row.id} onClick={()=>edit(row)} className={`d-calendar-task priority-${row.body.priority} ${row.body.status==='done'?'done':''}`}><i/>{row.body.time&&<span>{row.body.time} </span>}{row.body.title}</button>)}{list.length>(view==='week'?8:3)&&<button className="d-more-tasks" onClick={()=>choose(day)}>Ещё {list.length-(view==='week'?8:3)}</button>}</div><button className="d-cell-add" aria-label={`Добавить задачу ${formatDay(day)}`} onClick={()=>add(day)}><Plus size={16}/></button></div>;})}</div><p className="d-help d-calendar-help">Нажми на дату — расписание дня появится ниже. Задачу можно открыть и перенести.</p></section>;
}
function layout(tasks:TaskRow[]) {
  const sorted=tasks.filter(r=>r.body.time).map(row=>({row,start:timeMinutes(row.body.time!),end:timeMinutes(row.body.time!)+row.body.duration,lane:0,lanes:1})).sort((a,b)=>a.start-b.start||b.end-a.end);
  let group:typeof sorted=[], end=-1;
  const finish=()=>{const laneEnds:number[]=[];for(const item of group){let lane=laneEnds.findIndex(v=>v<=item.start);if(lane<0)lane=laneEnds.length;laneEnds[lane]=item.end;item.lane=lane;}for(const item of group)item.lanes=laneEnds.length;};
  for(const item of sorted){if(item.start>=end){finish();group=[];end=-1;}group.push(item);end=Math.max(end,item.end);}finish();return sorted;
}
export function Timeline({ date,tasks,projects,edit,add,compact=false }:{date:string;tasks:TaskRow[];projects:(Project&{id:string})[];edit:(row:TaskRow)=>void;add:(date:string,time?:string)=>void;compact?:boolean}) {
  const rows=tasks.filter(r=>r.body.date===date), blocks=layout(rows), min=Math.min(7,...blocks.map(b=>Math.floor(b.start/60))),max=Math.max(21,...blocks.map(b=>Math.ceil(b.end/60))), scale=compact ? 0.9 : 1.05;
  const now=new Date(), nowMinutes=now.getHours()*60+now.getMinutes();
  return <section className={`d-timeline-card ${compact?'compact':''}`}><div className="d-section-heading"><h2><ClockIcon/>План по часам</h2><span>{formatDay(date,{day:'numeric',month:'short'})}</span></div>{!!rows.filter(r=>!r.body.time).length&&<div className="d-all-day"><span>Без времени</span>{rows.filter(r=>!r.body.time).map(r=><button key={r.id} onClick={()=>edit(r)}>{r.body.title}</button>)}</div>}<div className="d-timeline-scroll"><div className="d-timeline" style={{height:(max-min)*60*scale+22} as CSSProperties}>{Array.from({length:max-min+1},(_,i)=>min+i).map(hour=><div className="d-hour" key={hour} style={{top:(hour-min)*60*scale}}><span>{String(hour).padStart(2,'0')}:00</span><button aria-label={`Добавить в ${hour}:00`} onClick={()=>add(date,`${String(hour).padStart(2,'0')}:00`)}><Plus size={13}/></button></div>)}{blocks.map(({row,start,end,lane,lanes})=>{const color=projects.find(p=>p.id===row.body.project)?.color||'#969dff';return <button className={`d-time-block ${row.body.status==='done'?'done':''}`} key={row.id} onClick={()=>edit(row)} style={{top:(start-min*60)*scale,height:Math.max(25,(end-start)*scale-3),left:`calc(51px + (100% - 58px) * ${lane/lanes})`,width:`calc((100% - 58px) / ${lanes} - 3px)`,'--block-color':color} as CSSProperties}><span>{row.body.time} · {durationLabel(row.body.duration)}</span><strong>{row.body.title}</strong>{row.body.source==='max'&&<small>От Макса</small>}</button>;})}{date===dayKey()&&nowMinutes>=min*60&&nowMinutes<=max*60&&<div className="d-now-line" style={{top:(nowMinutes-min*60)*scale}}><i/><span>{String(now.getHours()).padStart(2,'0')}:{String(now.getMinutes()).padStart(2,'0')}</span></div>}</div></div>{!blocks.length&&<p className="d-help">Нажми на свободное время, чтобы запланировать дело.</p>}</section>;
}
function ClockIcon(){return <CalendarDays size={17}/>;}
