import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { Play, Pause, RotateCcw, Coffee, Headphones, Check } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
import { dayKey, type TaskRow, type Change } from './lib/model';
export function FocusPanel({scope,tasks,selectedTask,save,capacity,setCapacity}:{scope:string;tasks:TaskRow[];selectedTask:string;save:(changes:Change[])=>Promise<unknown>;capacity:number;setCapacity:(v:number)=>void}) {
  const key='den-focus-'+scope;
  const [mode,setMode]=useState<'focus'|'break'>('focus'),[duration,setDuration]=useState(25),[remaining,setRemaining]=useState(1500),[target,setTarget]=useState<number|null>(null),[taskId,setTaskId]=useState(selectedTask||'none'),[runId,setRunId]=useState(''),[hydrated,setHydrated]=useState(false);
  const finished=useRef(false),audioRef=useRef<AudioContext|null>(null);
  useEffect(()=>{try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s&&['focus','break'].includes(s.mode)&&Number.isFinite(s.remaining)&&s.remaining>=0&&s.remaining<=10800&&Number.isInteger(s.duration)&&s.duration>=1&&s.duration<=180){setMode(s.mode);setDuration(s.duration);setRemaining(s.remaining);setTarget(typeof s.target==='number'?s.target:null);setTaskId(typeof s.taskId==='string'?s.taskId:'none');setRunId(typeof s.runId==='string'?s.runId:'');}}catch{}setHydrated(true);},[key]);
  useEffect(()=>{if(selectedTask&&!target)setTaskId(selectedTask);},[selectedTask,target]);
  useEffect(()=>{if(hydrated)try{localStorage.setItem(key,JSON.stringify({mode,duration,remaining,target,taskId,runId}));}catch{}},[key,hydrated,mode,duration,remaining,target,taskId,runId]);
  useEffect(()=>{if(target===null)return;finished.current=false;const tick=()=>{const seconds=Math.max(0,Math.ceil((target-Date.now())/1000));setRemaining(seconds);if(seconds===0&&!finished.current){finished.current=true;setTarget(null);toast.success(mode==='focus'?'Фокус завершён. Время передохнуть.':'Перерыв окончен. Можно продолжать.');try{const ctx=audioRef.current;if(ctx){const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=660;g.gain.setValueAtTime(.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.45);o.start();o.stop(ctx.currentTime+.45);}}catch{}if(mode==='focus'){const now=new Date().toISOString();void save([{id:'focus:'+runId,kind:'focus',body:{date:dayKey(),taskId:taskId==='none'?null:taskId,minutes:duration,completedAt:now}}]).catch(()=>toast.error('Не удалось сохранить сессию фокуса.'));}}};tick();const timer=setInterval(tick,250);return()=>clearInterval(timer);},[target,mode,duration,runId,taskId,save]);
  function start(){if(!audioRef.current)try{audioRef.current=new AudioContext();}catch{}void audioRef.current?.resume();if(!runId||remaining===0)setRunId(crypto.randomUUID());const value=remaining||duration*60;setRemaining(value);setTarget(Date.now()+value*1000);}
  function reset(nextMode=mode,minutes=duration){setTarget(null);setMode(nextMode);setDuration(minutes);setRemaining(minutes*60);setRunId('');}
  const percent=1-remaining/(duration*60);
  return <section className="d-focus-panel"><div className="d-focus-top"><span className="d-kicker">ОДНО ДЕЛО ЗА РАЗ</span><h2>Время сосредоточиться</h2><p>Выбери задачу и дай ей немного спокойного внимания.</p></div><div className="d-focus-mode"><button className={mode==='focus'?'selected':''} onClick={()=>reset('focus',25)} disabled={target!==null}><Headphones size={17}/>Фокус</button><button className={mode==='break'?'selected':''} onClick={()=>reset('break',5)} disabled={target!==null}><Coffee size={17}/>Перерыв</button></div><div className="d-focus-ring" style={{'--progress':`${Math.max(0,Math.min(1,percent))*360}deg`} as CSSProperties}><div><strong>{String(Math.floor(remaining/60)).padStart(2,'0')}<span>:</span>{String(remaining%60).padStart(2,'0')}</strong><span>{target?'Идёт время':remaining===0?'Готово':'В твоём темпе'}</span></div></div><div className="d-focus-controls"><button className="d-icon" onClick={()=>reset()} aria-label="Начать таймер заново"><RotateCcw/></button><button className="d-primary" onClick={()=>target?setTarget(null):start()}>{target?<Pause size={20}/>:<Play size={20}/>} {target?'Пауза':remaining===0?'Ещё раз':'Начать'}</button></div><div className="d-focus-settings"><label className="d-field"><span>Над чем работаешь?</span><Select value={taskId} onValueChange={setTaskId} disabled={target!==null}><SelectTrigger className="d-select"><SelectValue placeholder="Без привязки к задаче"/></SelectTrigger><SelectContent><SelectItem value="none">Без привязки к задаче</SelectItem>{tasks.filter(r=>r.body.status==='todo').map(r=><SelectItem key={r.id} value={r.id}>{r.body.title}</SelectItem>)}</SelectContent></Select></label><div className="d-duration-options">{(mode==='focus'?[15,25,45,60]:[5,10,15]).map(n=><button key={n} disabled={target!==null} className={duration===n?'selected':''} onClick={()=>reset(mode,n)}>{n} мин</button>)}</div></div><p className="d-help">Таймер учитывает реальное время, в том числе при переключении вкладок. Звук в фоне зависит от ограничений браузера.</p></section>;
}
