import { useRef, useState, type FormEvent } from 'react';
import { Cloud, CloudCheck, Download, Upload, RefreshCw, X, Smartphone, LockKeyhole, LogOut, Check, MessageSquare, CalendarDays, WifiOff } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { toast } from 'sonner';
import { backup, readBackup, type State } from './lib/sync-state';
import { readState, changeState } from './lib/store';
import { stage } from './lib/sync-state';
import { dayKey, parseDay, type Change, type Task, type TaskRow } from './lib/model';
import type { PlannerApi } from './use-planner';
export function download(name:string,contents:string,type='application/json'){const url=URL.createObjectURL(new Blob([contents],{type}));const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function calendarFile(tasks:TaskRow[]) {
  const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
  const utc=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');
  const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Den//Personal Planner//RU','CALSCALE:GREGORIAN','METHOD:PUBLISH'];
  for(const {id,body:t} of tasks.filter(r=>r.body.date&&r.body.status==='todo')){lines.push('BEGIN:VEVENT',`UID:${id}@den-planner`,`DTSTAMP:${utc(new Date())}`);if(t.time){const date=parseDay(t.date!);const [h,m]=t.time.split(':').map(Number);date.setHours(h,m,0,0);lines.push(`DTSTART:${utc(date)}`,`DTEND:${utc(new Date(date.getTime()+t.duration*60000))}`);}else{const date=parseDay(t.date!);date.setDate(date.getDate()+1);lines.push(`DTSTART;VALUE=DATE:${t.date!.replace(/-/g,'')}`,`DTEND;VALUE=DATE:${dayKey(date).replace(/-/g,'')}`);}lines.push(`SUMMARY:${escape(t.title)}`,`DESCRIPTION:${escape(t.notes+(t.deadline?'\nКрайний срок: '+t.deadline:''))}`,'END:VEVENT');}lines.push('END:VCALENDAR');
  return lines.map(line=>{let out='',part='',bytes=0;for(const char of line){const size=new TextEncoder().encode(char).length;if(bytes+size>73){out+=part+'\r\n ';part='';bytes=1;}part+=char;bytes+=size;}return out+part;}).join('\r\n')+'\r\n';
}
export function Settings({api,close,capacity,setCapacity,tasks,setupToken,activated}:{setupToken:string;activated:()=>void;api:PlannerApi;close:()=>void;capacity:number;setCapacity:(v:number)=>void;tasks:TaskRow[]}) {
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[regularLogin,setRegularLogin]=useState(false),[busy,setBusy]=useState(false),[imported,setImported]=useState<Change[]|null>(null),[notice,setNotice]=useState('');
  const input=useRef<HTMLInputElement>(null);
  const signup=!!setupToken&&!regularLogin;
  async function auth(e:FormEvent){
    e.preventDefault(); const client=api.cloud.client;if(!client)return;setBusy(true);setNotice('');
    try{
      if(signup){
        const response=await client.functions.invoke('planner-activate',{body:{token:setupToken,email:email.trim(),password}});
        if(response.error){let message='Не удалось подключить аккаунт. Проверь интернет и попробуй ещё раз.';try{const body=await response.error.context.json() as {error?:string};if(body.error)message=body.error;}catch{}throw new Error(message);}
        if(!response.data?.ok)throw new Error('Подключение не подтверждено. Попробуй ещё раз.');
        activated();setRegularLogin(true);
      }
      const {data,error}=await client.auth.signInWithPassword({email:email.trim(),password});
      if(error)throw new Error(error.code==='invalid_credentials'?'Проверь почту и пароль.':error.message);
      if(!data.session)throw new Error('Не удалось войти. Попробуй ещё раз.');
      setPassword('');toast.success('Аккаунт подключён. Загружаем твои задачи.');
    }catch(e){setNotice(e instanceof Error?e.message:'Не удалось войти.');}finally{setBusy(false);}
  }

  async function exportCopy(){try{download(`den-backup-${dayKey()}.json`,backup(await readState(api.scope)));toast.success('Резервная копия подготовлена');}catch(e){toast.error(e instanceof Error?e.message:'Не удалось подготовить копию.');}}
  async function selectFile(file?:File){if(!file)return;try{if(file.size>15000000)throw new Error('Максимальный размер копии — 15 МБ.');setImported(readBackup(await file.text()));}catch(e){toast.error(e instanceof Error?e.message:'Не удалось прочитать файл.');}finally{if(input.current)input.current.value='';}}
  async function restore(){if(!imported)return;setBusy(true);try{await changeState(api.scope,current=>{let next=current;for(let i=0;i<imported.length;i+=100)next=stage(next,imported.slice(i,i+100),!!api.session);return next;});await api.refresh();void api.sync();setImported(null);toast.success('Записи из копии восстановлены');}catch(e){toast.error(e instanceof Error?e.message:'Не удалось восстановить копию.');}finally{setBusy(false);}}
  return <><Dialog open onOpenChange={open=>{if(!open&&!busy)close();}}><DialogContent className="d-dialog d-settings" showCloseButton={false}><DialogHeader><div className="d-dialog-title"><DialogTitle>Настройки и связь</DialogTitle><DialogClose asChild><button className="d-icon" aria-label="Закрыть" disabled={busy}><X/></button></DialogClose></div><DialogDescription>Сохранение, резервная копия и задачи из чата.</DialogDescription></DialogHeader>
  <section className="d-connection-card"><div className="d-connection-icon">{api.session?<CloudCheck/>:<MessageSquare/>}</div><div><h3>Связь с Максом</h3><p>{api.cloud.loading?'Проверяем подключение…':api.session?'Задачи доступны в общей закрытой базе. Обновления приходят автоматически при подключении к интернету.':api.cloud.enabled?'Войди, чтобы я мог добавлять сюда задачи из нашего чата.':'Подключение общей базы ещё не завершено. Пока дела сохраняются только на этом телефоне.'}</p></div></section>
  {api.cloud.error&&<p className="d-error" role="alert">{api.cloud.error}</p>}
  {!api.cloud.enabled&&!api.cloud.loading&&<div className="d-setup-note"><LockKeyhole size={18}/><div><strong>Не удалось загрузить подключение</strong><p>Проверь интернет и нажми кнопку ниже. Локальные записи останутся на телефоне.</p><button className="d-secondary" onClick={()=>location.reload()}><RefreshCw size={16}/>Проверить подключение</button></div></div>}
  {api.cloud.enabled&&!api.session&&<form className="d-auth-form" onSubmit={auth}>{signup&&<p className="d-notice">Личная ссылка Макса. Придумай пароль для ежедневника — подтверждение по почте не потребуется.</p>}<label className="d-field"><span>Электронная почта</span><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Твоя почта"/></label><label className="d-field"><span>Пароль</span><input type="password" autoComplete={signup?'new-password':'current-password'} minLength={signup?12:1} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)} placeholder={signup?'Придумай пароль от 12 символов':'Пароль ежедневника'}/></label><button className="d-primary" disabled={busy}>{busy?'Подключаем…':signup?'Создать аккаунт':'Войти'}</button>{setupToken?<button className="d-link" type="button" onClick={()=>{setRegularLogin(!regularLogin);setNotice('');}}>{signup?'Уже создал аккаунт? Войти':'Подключить по личной ссылке'}</button>:<p className="d-help">Для первого входа открой личную ссылку подключения из нашего чата. Если забыл пароль, напиши Максу.</p>}{notice&&<p role="status" className="d-notice">{notice}</p>}</form>}
  {api.session&&<div className="d-account"><div><strong>{api.session.user.email}</strong><span>{api.syncing?'Обновляем…':Object.keys(api.state.pending).length?`Ждут отправки: ${Object.keys(api.state.pending).length}`:api.state.lastSync?'Синхронизировано в '+new Date(api.state.lastSync).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):'Первое подключение…'}</span></div><button className="d-icon" aria-label="Обновить задачи" disabled={api.syncing} onClick={()=>void api.sync()}><RefreshCw className={api.syncing?'d-spin':''}/></button><button className="d-secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const n=await api.migrateLocal();toast.success(n?`Перенесено записей: ${n}`:'Все локальные записи уже есть в аккаунте');}catch(e){toast.error(e instanceof Error?e.message:'Не удалось перенести записи.');}finally{setBusy(false);}}}>Перенести записи с телефона</button><button className="d-link" onClick={async()=>{const {error}=await api.cloud.client!.auth.signOut({scope:'local'});if(error)toast.error('Не удалось выйти.');}}><LogOut size={16}/>Выйти из аккаунта</button></div>}
  {api.syncError&&<p className="d-error" role="alert">{api.syncError}</p>}
  {!!Object.keys(api.state.conflicts).length&&<section className="d-conflicts"><h3>Выбери нужные версии</h3><p className="d-help">Запись изменили одновременно. Оба варианта сохранены до твоего выбора.</p>{Object.values(api.state.conflicts).map(c=><div key={c.id}><strong>{c.local.kind==='task'?(c.local.body as Task).title:c.local.kind==='note'?'Заметка дня':'Запись'}</strong><p>На телефоне: {c.local.deleted?'удалено':c.local.kind==='task'?`${(c.local.body as Task).date||'без даты'} · ${(c.local.body as Task).status==='done'?'выполнено':'не выполнено'}`:JSON.stringify(c.local.body).slice(0,180)}</p><p>В общей базе: {!c.remote||c.remote.deleted?'удалено / не создано':c.remote.kind==='task'?`${(c.remote.body as Task).title} · ${(c.remote.body as Task).date||'без даты'} · ${(c.remote.body as Task).status==='done'?'выполнено':'не выполнено'}`:JSON.stringify(c.remote.body).slice(0,180)}</p><div><button className="d-secondary" onClick={()=>void api.resolve(c.id,'local').catch(()=>toast.error('Не удалось выбрать версию.'))}>Оставить с телефона</button><button className="d-secondary" onClick={()=>void api.resolve(c.id,'remote').catch(()=>toast.error('Не удалось выбрать версию.'))}>Взять из общей базы</button></div></div>)}</section>}
  <section className="d-settings-section"><h3>Резервная копия</h3><p>Сохрани файл перед сменой телефона или очисткой браузера.</p><div className="d-settings-buttons"><button className="d-secondary" onClick={()=>void exportCopy()}><Download size={17}/>Скачать копию</button><button className="d-secondary" onClick={()=>input.current?.click()}><Upload size={17}/>Восстановить</button><button className="d-secondary" onClick={()=>download(`den-calendar-${dayKey()}.ics`,calendarFile(tasks),'text/calendar;charset=utf-8')}><CalendarDays size={17}/>Выгрузить календарь</button></div><p className="d-help">Файл календаря можно импортировать в Google Calendar. Это разовая копия расписания.</p><input ref={input} type="file" accept=".json,application/json" hidden onChange={e=>void selectFile(e.target.files?.[0])}/></section>
  <section className="d-settings-section"><label className="d-field"><span>Сколько часов планировать на день?</span><input type="number" min={1} max={16} step={.5} value={capacity/60} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=16)setCapacity(n*60);}}/></label><p className="d-help">Если план длиннее, ежедневник покажет перегрузку. Это ориентир, а не ограничение.</p></section><div className="d-device-note"><Smartphone size={17}/><span>Без сети можно работать с сохранённой версией. В аккаунте изменения отправятся при восстановлении связи. Записи без входа можно перенести кнопкой выше.</span></div>
  </DialogContent></Dialog><AlertDialog open={!!imported} onOpenChange={open=>{if(!open&&!busy)setImported(null);}}><AlertDialogContent className="d-dialog"><AlertDialogHeader><AlertDialogTitle>Восстановить записи?</AlertDialogTitle><AlertDialogDescription>В файле {imported?.length} записей. Новые добавятся, совпадающие по номеру заменятся версиями из файла. Остальные текущие записи останутся. Перед восстановлением можно скачать текущую копию.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Отмена</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void restore();}}>{busy?'Восстанавливаем…':'Восстановить'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
