import { useState, type FormEvent } from 'react';
import { Check, Plus, Trash2, X, CalendarDays, Clock3, Flag, Repeat2 } from 'lucide-react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetClose } from '@/components/ui/sheet';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
import { PRIORITIES, REPEATS, parseDay, validateBody, type Task, type Project, type Priority, type Repeat } from './lib/model';
export type Editor = { id: string; body: Task; existing: boolean; originalUpdatedAt?: string; revision?: number };
export function TaskEditor({ draft, projects, close, save, remove }: { draft: Editor; projects: (Project & {id:string})[]; close: () => void; save: (draft: Editor) => Promise<void>; remove: () => void }) {
  const [task,setTask] = useState(draft.body), [busy,setBusy] = useState(false), [step,setStep] = useState(''), [tagsText,setTagsText] = useState(draft.body.tags.join(', ')), [advanced,setAdvanced] = useState(draft.body.repeat.frequency !== 'none' || !!draft.body.deadline || !!draft.body.tags.length);
  const update = (patch: Partial<Task>) => setTask(t => ({...t,...patch}));
  const setDate = (value: string) => update({date: value || null,...(!value ? {time:null,repeat:{...task.repeat,frequency:'none'}} : {repeat:{...task.repeat,anchorDay:parseDay(value).getDate()}})});
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { await save({...draft,body:validateBody('task',{...task,tags:tagsText.split(',').map(s=>s.trim()).filter(Boolean),updatedAt:new Date().toISOString()}) as Task}); close(); } catch (e) { toast.error(e instanceof Error ? e.message : 'Не удалось сохранить задачу.'); } finally { setBusy(false); } }
  function addStep() { if (!step.trim()) return; update({checklist:[...task.checklist,{id:crypto.randomUUID(),text:step.trim(),done:false}]}); setStep(''); }
  return <Sheet open onOpenChange={open => { if (!open && !busy) close(); }}><SheetContent className="d-sheet" showCloseButton={false}><SheetHeader className="d-sheet-heading"><div><span className="d-kicker">{draft.existing ? 'ДЕТАЛИ ЗАДАЧИ' : 'НОВАЯ ЗАДАЧА'}</span><SheetTitle>{draft.existing ? 'Всё по делу' : 'Что нужно сделать?'}</SheetTitle></div><SheetClose asChild><button type="button" className="d-icon" aria-label="Закрыть" disabled={busy}><X/></button></SheetClose><SheetDescription className="sr-only">Название, план, срок и шаги задачи.</SheetDescription></SheetHeader>
  <form onSubmit={submit} className="d-editor-form"><label className="d-field"><span>Задача</span><textarea className="d-title-input" value={task.title} onChange={e => update({title:e.target.value})} placeholder="Например, подготовить предложение клиенту" maxLength={300} rows={2} required autoFocus /></label>
  <label className="d-field"><span>Проект</span><Select value={task.project} onValueChange={project => update({project})}><SelectTrigger className="d-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="inbox">Входящие</SelectItem>{projects.map(p => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></label>
  <div className="d-form-grid"><label className="d-field"><span><CalendarDays size={16}/>Планирую сделать</span><input type="date" min="2000-01-01" max="2199-12-31" value={task.date || ''} onChange={e => setDate(e.target.value)}/></label><label className="d-field"><span><Clock3 size={16}/>Начало</span><input type="time" disabled={!task.date} value={task.time || ''} onChange={e => update({time:e.target.value || null})}/></label><label className="d-field"><span>Длительность, мин</span><input type="number" min={5} max={720} step={5} value={task.duration} onChange={e => update({duration:Number(e.target.value)})}/></label><label className="d-field"><span><Flag size={16}/>Приоритет</span><Select value={String(task.priority)} onValueChange={value => update({priority:Number(value) as Priority})}><SelectTrigger className={`d-select priority-${task.priority}`}><SelectValue/></SelectTrigger><SelectContent>{PRIORITIES.map((label,i) => <SelectItem key={i} value={String(i)}>{label}</SelectItem>)}</SelectContent></Select></label></div>
  <label className="d-check-label"><Checkbox checked={task.starred} onCheckedChange={value => update({starred:value === true})}/>Выделить как главное</label>
  <button type="button" className="d-link" onClick={() => setAdvanced(!advanced)}>{advanced ? 'Скрыть дополнительные настройки' : 'Повторение, крайний срок и метки'}</button>
  {advanced && <div className="d-advanced"><label className="d-field"><span><Repeat2 size={16}/>Повторение</span><Select value={task.repeat.frequency} onValueChange={frequency => update({repeat:{...task.repeat,frequency:frequency as Repeat['frequency']}})}><SelectTrigger className="d-select"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(REPEATS).map(([key,label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></label>{task.repeat.frequency !== 'none' && <><div className="d-form-grid"><label className="d-field"><span>Каждый N-й период</span><input type="number" min={1} max={365} value={task.repeat.interval} onChange={e => update({repeat:{...task.repeat,interval:Number(e.target.value)}})}/></label><label className="d-field"><span>Повторять до</span><input type="date" min={task.date || '2000-01-01'} max="2199-12-31" value={task.repeat.until || ''} onChange={e => update({repeat:{...task.repeat,until:e.target.value || null}})}/></label></div><p className="d-help">После выполнения появится ближайшее следующее повторение. Пропущенные даты не отмечаются выполненными.</p></>}
  <label className="d-field"><span>Крайний срок</span><input type="date" min="2000-01-01" max="2199-12-31" value={task.deadline || ''} onChange={e => update({deadline:e.target.value || null})}/></label><p className="d-help">План можно перенести. Крайний срок останется прежним.</p><label className="d-field"><span>Метки через запятую</span><input value={tagsText} onChange={e => setTagsText(e.target.value)} placeholder="звонок, документы" maxLength={800}/></label></div>}
  <label className="d-field"><span>Заметки</span><textarea value={task.notes} rows={3} onChange={e => update({notes:e.target.value})} maxLength={20000} placeholder="Детали, мысли, ссылка…"/></label>
  <div className="d-field"><span>Шаги {task.checklist.length ? `${task.checklist.filter(c => c.done).length}/${task.checklist.length}` : ''}</span><div className="d-checklist">{task.checklist.map(c => <div key={c.id}><Checkbox aria-label={`Готово: ${c.text}`} checked={c.done} onCheckedChange={value => update({checklist:task.checklist.map(s => s.id===c.id ? {...s,done:value===true} : s)})}/><input aria-label="Текст шага" value={c.text} maxLength={300} onChange={e => update({checklist:task.checklist.map(s => s.id===c.id ? {...s,text:e.target.value} : s)})}/><button type="button" className="d-icon" aria-label="Удалить шаг" onClick={() => update({checklist:task.checklist.filter(s => s.id!==c.id)})}><X size={16}/></button></div>)}</div><div className="d-new-step"><input value={step} maxLength={300} onChange={e => setStep(e.target.value)} placeholder="Добавить шаг" onKeyDown={e => { if(e.key==='Enter'){e.preventDefault();addStep();} }}/><button type="button" className="d-icon" disabled={!step.trim() || task.checklist.length>=100} aria-label="Добавить шаг" onClick={addStep}><Plus/></button></div></div>
  <div className="d-editor-actions">{draft.existing && <button type="button" className="d-icon d-danger" aria-label="Удалить задачу" disabled={busy} onClick={remove}><Trash2/></button>}<button className="d-primary" disabled={busy || !task.title.trim()}><Check size={18}/>{busy ? 'Сохраняем…' : 'Сохранить задачу'}</button></div>
  </form></SheetContent></Sheet>;
}
